# Generated by Django 5.0.4 on 2024-04-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0002_auto_20180520_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='authenticationrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
